### ISSUE TITLE
Where should I put my input?

### ISSUE THREAD

**Issue by halynyu** [flywheel-apps/fwgear-wsi-to-dicom-converter#7]
Hi,
I want to run the file I want in this code. But I don't know where to put the Input File and run this code.
First of all, I tried specifying a path like "Input_file = ...". And I tried creating a folder called Input_file, inserting an svs file, and run code.
But All of this didn't all work properly.
Can you tell me where and how to put my svs file to turn this code well?

**Comment by NPann** [comment]
Hi @halynyu. This Flywheel gear is wrapping https://github.com/GoogleCloudPlatform/wsi-to-dicom-converter for performing the conversion. For performing this conversion outside of Flywheel you might be better off just using this package instead. Thanks !
